INSERT INTO pipeline.deteccion (objectid, id, info)
VALUES ('lamejorllave', uuid(), {'fid': 1.0, 'magpsf': 2.5, 'sigmapsf': 2.6, 'magpsf_corr': 1.1, 'sigmapsf_corr': 1.0, 'jd': 3.0});
INSERT INTO pipeline.deteccion (objectid, id, info)
VALUES ('lamejorllave', uuid(), {'fid': 2.0, 'magpsf': 2.5, 'sigmapsf': 2.6, 'magpsf_corr': 1.1, 'sigmapsf_corr': 1.0, 'jd': 3.0});
INSERT INTO pipeline.deteccion (objectid, id, info)
VALUES ('lamejorllave', uuid(), {'fid': 3.0, 'magpsf': 2.5, 'sigmapsf': 2.6, 'magpsf_corr': 1.1, 'sigmapsf_corr': 1.0, 'jd': 3.0});
INSERT INTO pipeline.deteccion (objectid, id, info)
VALUES ('lamejorllave', uuid(), {'fid': 1.0, 'magpsf': 2.5, 'sigmapsf': 2.6, 'magpsf_corr': 1.1, 'sigmapsf_corr': 1.0, 'jd': 3.0});
